"""Make user_id nullable

Revision ID: 193a6e116e6c
Revises: 9d3ba1ead1a7
Create Date: 2025-07-01 03:49:29.475668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193a6e116e6c'
down_revision = '9d3ba1ead1a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
